// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MemberOnline.proto

package com.yanxiu.im.protobuf;

/**
 * APP端的离线、上线事件设置
 * wiki :http://wiki.yanxiu.com/pages/viewpage.action?pageId=12326692
 */
public final class MemberOnlineProto {
  private MemberOnlineProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface MemberOnlineOrBuilder extends
      // @@protoc_insertion_point(interface_extends:MemberOnline)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 bizSource = 1;</code>
     */
    int getBizSource();

    /**
     * <code>int64 memberId = 2;</code>
     */
    long getMemberId();

    /**
     * <code>string token = 3;</code>
     */
    String getToken();
    /**
     * <code>string token = 3;</code>
     */
    com.google.protobuf.ByteString
        getTokenBytes();

    /**
     * <code>int32 onlineType = 4;</code>
     */
    int getOnlineType();

    /**
     * <code>int32 onlineState = 5;</code>
     */
    int getOnlineState();
  }
  /**
   * Protobuf type {@code MemberOnline}
   */
  public  static final class MemberOnline extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:MemberOnline)
      MemberOnlineOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use MemberOnline.newBuilder() to construct.
    private MemberOnline(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private MemberOnline() {
      bizSource_ = 0;
      memberId_ = 0L;
      token_ = "";
      onlineType_ = 0;
      onlineState_ = 0;
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private MemberOnline(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              bizSource_ = input.readInt32();
              break;
            }
            case 16: {

              memberId_ = input.readInt64();
              break;
            }
            case 26: {
              String s = input.readStringRequireUtf8();

              token_ = s;
              break;
            }
            case 32: {

              onlineType_ = input.readInt32();
              break;
            }
            case 40: {

              onlineState_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.yanxiu.im.protobuf.MemberOnlineProto.internal_static_MemberOnline_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.yanxiu.im.protobuf.MemberOnlineProto.internal_static_MemberOnline_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.yanxiu.im.protobuf.MemberOnlineProto.MemberOnline.class, com.yanxiu.im.protobuf.MemberOnlineProto.MemberOnline.Builder.class);
    }

    public static final int BIZSOURCE_FIELD_NUMBER = 1;
    private int bizSource_;
    /**
     * <code>int32 bizSource = 1;</code>
     */
    public int getBizSource() {
      return bizSource_;
    }

    public static final int MEMBERID_FIELD_NUMBER = 2;
    private long memberId_;
    /**
     * <code>int64 memberId = 2;</code>
     */
    public long getMemberId() {
      return memberId_;
    }

    public static final int TOKEN_FIELD_NUMBER = 3;
    private volatile Object token_;
    /**
     * <code>string token = 3;</code>
     */
    public String getToken() {
      Object ref = token_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        token_ = s;
        return s;
      }
    }
    /**
     * <code>string token = 3;</code>
     */
    public com.google.protobuf.ByteString
        getTokenBytes() {
      Object ref = token_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        token_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ONLINETYPE_FIELD_NUMBER = 4;
    private int onlineType_;
    /**
     * <code>int32 onlineType = 4;</code>
     */
    public int getOnlineType() {
      return onlineType_;
    }

    public static final int ONLINESTATE_FIELD_NUMBER = 5;
    private int onlineState_;
    /**
     * <code>int32 onlineState = 5;</code>
     */
    public int getOnlineState() {
      return onlineState_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (bizSource_ != 0) {
        output.writeInt32(1, bizSource_);
      }
      if (memberId_ != 0L) {
        output.writeInt64(2, memberId_);
      }
      if (!getTokenBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, token_);
      }
      if (onlineType_ != 0) {
        output.writeInt32(4, onlineType_);
      }
      if (onlineState_ != 0) {
        output.writeInt32(5, onlineState_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (bizSource_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, bizSource_);
      }
      if (memberId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, memberId_);
      }
      if (!getTokenBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, token_);
      }
      if (onlineType_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, onlineType_);
      }
      if (onlineState_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, onlineState_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.yanxiu.im.protobuf.MemberOnlineProto.MemberOnline)) {
        return super.equals(obj);
      }
      com.yanxiu.im.protobuf.MemberOnlineProto.MemberOnline other = (com.yanxiu.im.protobuf.MemberOnlineProto.MemberOnline) obj;

      boolean result = true;
      result = result && (getBizSource()
          == other.getBizSource());
      result = result && (getMemberId()
          == other.getMemberId());
      result = result && getToken()
          .equals(other.getToken());
      result = result && (getOnlineType()
          == other.getOnlineType());
      result = result && (getOnlineState()
          == other.getOnlineState());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + BIZSOURCE_FIELD_NUMBER;
      hash = (53 * hash) + getBizSource();
      hash = (37 * hash) + MEMBERID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getMemberId());
      hash = (37 * hash) + TOKEN_FIELD_NUMBER;
      hash = (53 * hash) + getToken().hashCode();
      hash = (37 * hash) + ONLINETYPE_FIELD_NUMBER;
      hash = (53 * hash) + getOnlineType();
      hash = (37 * hash) + ONLINESTATE_FIELD_NUMBER;
      hash = (53 * hash) + getOnlineState();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.yanxiu.im.protobuf.MemberOnlineProto.MemberOnline parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.yanxiu.im.protobuf.MemberOnlineProto.MemberOnline parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.yanxiu.im.protobuf.MemberOnlineProto.MemberOnline parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.yanxiu.im.protobuf.MemberOnlineProto.MemberOnline parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.yanxiu.im.protobuf.MemberOnlineProto.MemberOnline parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.yanxiu.im.protobuf.MemberOnlineProto.MemberOnline parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.yanxiu.im.protobuf.MemberOnlineProto.MemberOnline parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.yanxiu.im.protobuf.MemberOnlineProto.MemberOnline parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.yanxiu.im.protobuf.MemberOnlineProto.MemberOnline parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.yanxiu.im.protobuf.MemberOnlineProto.MemberOnline parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.yanxiu.im.protobuf.MemberOnlineProto.MemberOnline parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.yanxiu.im.protobuf.MemberOnlineProto.MemberOnline parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.yanxiu.im.protobuf.MemberOnlineProto.MemberOnline prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code MemberOnline}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:MemberOnline)
        com.yanxiu.im.protobuf.MemberOnlineProto.MemberOnlineOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.yanxiu.im.protobuf.MemberOnlineProto.internal_static_MemberOnline_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.yanxiu.im.protobuf.MemberOnlineProto.internal_static_MemberOnline_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.yanxiu.im.protobuf.MemberOnlineProto.MemberOnline.class, com.yanxiu.im.protobuf.MemberOnlineProto.MemberOnline.Builder.class);
      }

      // Construct using com.yanxiu.im.protobuf.MemberOnlineProto.MemberOnline.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        bizSource_ = 0;

        memberId_ = 0L;

        token_ = "";

        onlineType_ = 0;

        onlineState_ = 0;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.yanxiu.im.protobuf.MemberOnlineProto.internal_static_MemberOnline_descriptor;
      }

      public com.yanxiu.im.protobuf.MemberOnlineProto.MemberOnline getDefaultInstanceForType() {
        return com.yanxiu.im.protobuf.MemberOnlineProto.MemberOnline.getDefaultInstance();
      }

      public com.yanxiu.im.protobuf.MemberOnlineProto.MemberOnline build() {
        com.yanxiu.im.protobuf.MemberOnlineProto.MemberOnline result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.yanxiu.im.protobuf.MemberOnlineProto.MemberOnline buildPartial() {
        com.yanxiu.im.protobuf.MemberOnlineProto.MemberOnline result = new com.yanxiu.im.protobuf.MemberOnlineProto.MemberOnline(this);
        result.bizSource_ = bizSource_;
        result.memberId_ = memberId_;
        result.token_ = token_;
        result.onlineType_ = onlineType_;
        result.onlineState_ = onlineState_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.yanxiu.im.protobuf.MemberOnlineProto.MemberOnline) {
          return mergeFrom((com.yanxiu.im.protobuf.MemberOnlineProto.MemberOnline)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.yanxiu.im.protobuf.MemberOnlineProto.MemberOnline other) {
        if (other == com.yanxiu.im.protobuf.MemberOnlineProto.MemberOnline.getDefaultInstance()) return this;
        if (other.getBizSource() != 0) {
          setBizSource(other.getBizSource());
        }
        if (other.getMemberId() != 0L) {
          setMemberId(other.getMemberId());
        }
        if (!other.getToken().isEmpty()) {
          token_ = other.token_;
          onChanged();
        }
        if (other.getOnlineType() != 0) {
          setOnlineType(other.getOnlineType());
        }
        if (other.getOnlineState() != 0) {
          setOnlineState(other.getOnlineState());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.yanxiu.im.protobuf.MemberOnlineProto.MemberOnline parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.yanxiu.im.protobuf.MemberOnlineProto.MemberOnline) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int bizSource_ ;
      /**
       * <code>int32 bizSource = 1;</code>
       */
      public int getBizSource() {
        return bizSource_;
      }
      /**
       * <code>int32 bizSource = 1;</code>
       */
      public Builder setBizSource(int value) {

        bizSource_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 bizSource = 1;</code>
       */
      public Builder clearBizSource() {

        bizSource_ = 0;
        onChanged();
        return this;
      }

      private long memberId_ ;
      /**
       * <code>int64 memberId = 2;</code>
       */
      public long getMemberId() {
        return memberId_;
      }
      /**
       * <code>int64 memberId = 2;</code>
       */
      public Builder setMemberId(long value) {

        memberId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 memberId = 2;</code>
       */
      public Builder clearMemberId() {

        memberId_ = 0L;
        onChanged();
        return this;
      }

      private Object token_ = "";
      /**
       * <code>string token = 3;</code>
       */
      public String getToken() {
        Object ref = token_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          token_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string token = 3;</code>
       */
      public com.google.protobuf.ByteString
          getTokenBytes() {
        Object ref = token_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          token_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string token = 3;</code>
       */
      public Builder setToken(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }

        token_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string token = 3;</code>
       */
      public Builder clearToken() {

        token_ = getDefaultInstance().getToken();
        onChanged();
        return this;
      }
      /**
       * <code>string token = 3;</code>
       */
      public Builder setTokenBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

        token_ = value;
        onChanged();
        return this;
      }

      private int onlineType_ ;
      /**
       * <code>int32 onlineType = 4;</code>
       */
      public int getOnlineType() {
        return onlineType_;
      }
      /**
       * <code>int32 onlineType = 4;</code>
       */
      public Builder setOnlineType(int value) {

        onlineType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 onlineType = 4;</code>
       */
      public Builder clearOnlineType() {

        onlineType_ = 0;
        onChanged();
        return this;
      }

      private int onlineState_ ;
      /**
       * <code>int32 onlineState = 5;</code>
       */
      public int getOnlineState() {
        return onlineState_;
      }
      /**
       * <code>int32 onlineState = 5;</code>
       */
      public Builder setOnlineState(int value) {

        onlineState_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 onlineState = 5;</code>
       */
      public Builder clearOnlineState() {

        onlineState_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:MemberOnline)
    }

    // @@protoc_insertion_point(class_scope:MemberOnline)
    private static final com.yanxiu.im.protobuf.MemberOnlineProto.MemberOnline DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.yanxiu.im.protobuf.MemberOnlineProto.MemberOnline();
    }

    public static com.yanxiu.im.protobuf.MemberOnlineProto.MemberOnline getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<MemberOnline>
        PARSER = new com.google.protobuf.AbstractParser<MemberOnline>() {
      public MemberOnline parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new MemberOnline(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<MemberOnline> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<MemberOnline> getParserForType() {
      return PARSER;
    }

    public com.yanxiu.im.protobuf.MemberOnlineProto.MemberOnline getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_MemberOnline_descriptor;
  private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_MemberOnline_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\022MemberOnline.proto\"k\n\014MemberOnline\022\021\n\t" +
      "bizSource\030\001 \001(\005\022\020\n\010memberId\030\002 \001(\003\022\r\n\005tok" +
      "en\030\003 \001(\t\022\022\n\nonlineType\030\004 \001(\005\022\023\n\013onlineSt" +
      "ate\030\005 \001(\005B(\n\023com.yanxiu.im.protoB\021Member" +
      "OnlineProtob\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_MemberOnline_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_MemberOnline_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_MemberOnline_descriptor,
        new String[] { "BizSource", "MemberId", "Token", "OnlineType", "OnlineState", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
